# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_db_logger}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phil Burrows", "Alex Stupka"]
  s.date = %q{2010-10-05}
  s.description = %q{Centralized logging for rails apps in MongoDB. The idea and most of the code is from http://github.com/peburrows/mongo_db_logger}
  s.email = %q{alex.stupka@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/mongo_db_logger.rb",
     "lib/mongo_db_logging.rb",
     "lib/mongo_db_logging/mongo_controller.rb",
     "lib/mongo_db_logging/routing_extensions.rb",
     "lib/mongo_logger.rb",
     "views/mongo_db_logging/mongo/index.html.erb"
  ]
  s.homepage = %q{http://github.com/customink/mongo_db_logger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{mongo_db_logger}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby Mongo DB Logger for Rails}
  s.test_files = [
    "test/blueprints.rb",
     "test/helper.rb",
     "test/unit/test_mongo_db_logger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 0"])
    else
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
  end
end

